/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/hatsune_miku_v6.glb --transform 
Files: public/hatsune_miku_v6.glb [8.58MB] > C:\Users\Gehdron\Documents\GitHub\Study Gacha\study-gacha\hatsune_miku_v6-transformed.glb [1.17MB] (86%)
Author: not_here01-39 (https://sketchfab.com/not_here01-39)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hatsune-miku-v6-14c9c7a0348842d79973bd1c9da29bb4
Title: Hatsune Miku V6
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hatsune_miku_v6-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.cloth0} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.cloth21} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.skirt2} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.pants4} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.longhair9} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.fronthair10} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.backhair11} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.metal12} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.shoes14} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.eyes19} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.eyelashes20} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['0130']} />
    </group>
  )
}

useGLTF.preload('/hatsune_miku_v6-transformed.glb')
